//
//  ArticleDetailsInteractor.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsInteractor: ArticleDetailsInteractorProtocol {

    weak var presenter: ArticleDetailsPresenterProtocol?
}
