//
//  ArticleDetailsPresenter.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsPresenter: ArticleDetailsPresenterProtocol {

    weak private var view: ArticleDetailsViewProtocol?
    var interactor: ArticleDetailsInteractorProtocol?
    private let router: ArticleDetailsWireframeProtocol

    init(interface: ArticleDetailsViewProtocol, interactor: ArticleDetailsInteractorProtocol?, router: ArticleDetailsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
