//
//  ArticleDetailsPresenter.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsPresenter: ArticleDetailsPresenterProtocol {

    weak private var view: ArticleDetailsViewProtocol?
    var interactor: ArticleDetailsInteractorProtocol?
    private let router: ArticleDetailsWireframeProtocol
	var viewModel: ArticleDetailsViewModel

    init(interface: ArticleDetailsViewProtocol, interactor: ArticleDetailsInteractorProtocol?, router: ArticleDetailsWireframeProtocol, newsArticle: NewsArticle) {
        self.view = interface
        self.interactor = interactor
        self.router = router
		viewModel = ArticleDetailsViewModel(article: newsArticle)
    }

}

extension ArticleDetailsPresenter {

	var articleImages: [String]? {
		return viewModel.articleImages
	}

	var articleTitle: String {
		return viewModel.articleTitle
	}

	var articleDate: String {
		return viewModel.articleDate
	}

	var articleSection: String {
		return viewModel.articleSection
	}

	var articleAbstract: String {
		return viewModel.articleAbstract
	}

	var articleByLine: String {
		return viewModel.articleByLine
	}

}
