//
//  NYTMostViewdArticlesPresenter.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/3/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NYTMostViewdArticlesPresenter {

    weak private var view: NYTMostViewdArticlesViewProtocol?
    var interactor: NYTMostViewdArticlesInteractorProtocol?
    private let router: NYTMostViewdArticlesWireframeProtocol

    init(interface: NYTMostViewdArticlesViewProtocol, interactor: NYTMostViewdArticlesInteractorProtocol?, router: NYTMostViewdArticlesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension NYTMostViewdArticlesPresenter: NYTMostViewdArticlesPresenterProtocol {
	
	func getMostViewdNews() {
		view?.startLoadingAnimation()
		interactor?.fetchNewsWith(period: .week)
	}
	
	func fetchNewsSuccessful(news: [NewsArticle]) {
		view?.stopLoadingAnimation()
	}
	
	func fetchNewsFailure(error: Error) {
		view?.stopLoadingAnimation()
	}
}
