//
//  ArticleDetailsProtocols.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol ArticleDetailsWireframeProtocol: class {

}
// MARK: Presenter -
protocol ArticleDetailsPresenterProtocol: class {
	var viewModel: ArticleDetailsViewModel { get set }
}

// MARK: Interactor -
protocol ArticleDetailsInteractorProtocol: class {

  var presenter: ArticleDetailsPresenterProtocol? { get set }
}

// MARK: View -
protocol ArticleDetailsViewProtocol: class {

  var presenter: ArticleDetailsPresenterProtocol? { get set }
}
