//
//  NYTMostViewdArticlesInteractor.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/3/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NYTMostViewdArticlesInteractor: NYTMostViewdArticlesInteractorProtocol {

    weak var presenter: NYTMostViewdArticlesPresenterProtocol?
	
	
}
