//
//  ArticleDetailsRouter.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsRouter: ArticleDetailsWireframeProtocol {

    weak var viewController: UIViewController?

	static func createModule(with artiicle: NewsArticle) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ArticleDetailsViewController(nibName: nil, bundle: nil)
        let interactor = ArticleDetailsInteractor()
        let router = ArticleDetailsRouter()
		let presenter = ArticleDetailsPresenter(interface: view, interactor: interactor, router: router, newsArticle: artiicle)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
