//
//  NYTMostViewdArticlesViewController.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/3/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NYTMostViewdArticlesViewController: UIViewController, NYTMostViewdArticlesViewProtocol {

	var presenter: NYTMostViewdArticlesPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
