//
//  ArticleDetailsViewController.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsViewController: UIViewController, ArticleDetailsViewProtocol {

	var presenter: ArticleDetailsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
