//
//  ArticleDetailsViewController.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/4/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticleDetailsViewController: UIViewController, ArticleDetailsViewProtocol {

	@IBOutlet weak var topInfoView: TopInfoView!
	@IBOutlet weak var articleTitle: UILabel!
	@IBOutlet weak var articleSection: UILabel!
	@IBOutlet weak var articleDate: UILabel!
	@IBOutlet weak var articleByline: UILabel!
	@IBOutlet weak var articleAbstract: UILabel!

	var presenter: ArticleDetailsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
		setUpUI()
    }

	func setUpUI() {
		topInfoView.setup(with: presenter?.viewModel.articleImages ?? [])
		articleDate.text = presenter?.viewModel.articleDate
		articleSection.text = presenter?.viewModel.articleSection
		articleTitle.text = presenter?.viewModel.articleTitle
		articleAbstract.text = presenter?.viewModel.articleAbstract
		articleByline.text = presenter?.viewModel.articleByLine
	}

}
