# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MostPopularArticles' do
  use_frameworks!
	
	pod 'SwiftLint'

  target 'MostPopularArticlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MostPopularArticlesUITests' do
    # Pods for testing
  end

end
