# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MostPopularArticles' do
  use_frameworks!
	
  pod 'Moya', '13.0.1'
  # Pods for MostPopularArticles

  target 'MostPopularArticlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MostPopularArticlesUITests' do
    # Pods for testing
  end

end
