//
//  NYTMostViewdArticlesProtocols.swift
//  MostPopularArticles
//
//  Created Abanoub Nabil on 12/3/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NYTMostViewdArticlesWireframeProtocol: class {

}
//MARK: Presenter -
protocol NYTMostViewdArticlesPresenterProtocol: class {

}

//MARK: Interactor -
protocol NYTMostViewdArticlesInteractorProtocol: class {

  var presenter: NYTMostViewdArticlesPresenterProtocol?  { get set }
}

//MARK: View -
protocol NYTMostViewdArticlesViewProtocol: class {

  var presenter: NYTMostViewdArticlesPresenterProtocol?  { get set }
}
